language: ruby

rvm:
  - 2.5.3

services:
  - docker

script:
  - docker-compose build
  - docker-compose ps
  - docker container ls
  - docker-compose run ror rails db:create
  - docker-compose run ror rails test
