language: ruby

rvm:
  - 2.5.3

services:
  - docker

install:
  - npm install -g @angular/cli

script:
  - docker-compose build
  - docker container -ls
  - docker-compose ps
  - docker-compose run ror rails db:create
  - docker-compose run ror rails test
  - docker-compose run ng npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
  - docker-compose run ng npm run e2e
  - docker-compose stop
