language: ruby

rvm:
  - 2.5.3

services:
  - docker

script:
  - docker-compose up --build
  - docker-compose ps
  - docker-compose run ror rails db:create
  - docker-compose run ror rails test
  - docker-compose stop
  - shutdown now
